trigger:
  branches:
    include:
      - main  # This will trigger the pipeline when changes are pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image for the build environment

steps:
# Step 1: Checkout the code from GitHub repository
- task: Checkout@1
  displayName: 'Checkout code'

# Step 2: Set up Node.js (example for Node.js project)
- task: UseNode@1
  inputs:
    versionSpec: '14.x'  # Use Node.js version 14
  displayName: 'Set up Node.js'

# Step 3: Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Step 4: Run tests
- script: npm test
  displayName: 'Run tests'

# Step 5: Build the project
- script: npm run build
  displayName: 'Build project'
